import { Risk, Owner, User } from './types';

export const initialOwners: Owner[] = [
  { id: '1', name: 'Alice Johnson', department: 'Engineering' },
  { id: '2', name: 'Bob Williams', department: 'Product' },
  { id: '3', name: 'Charlie Brown', department: 'Marketing' },
  { id: '4', name: 'Diana Miller', department: 'HR' },
];

export const initialUsers: User[] = [
  { id: 'u1', name: 'Sam', role: 'user', department: 'Engineering' },
  { id: 'u2', name: 'Maya', role: 'manager', department: 'Engineering' },
  { id: 'u3', name: 'Alex', role: 'admin' },
];

export const initialRisks: Risk[] = [
  {
    id: 'r0',
    riskNo: 'R003',
    name: 'Legacy Service Capacity Risk',
    description: 'User-reported capacity constraints in the legacy service layer may cause intermittent slowdowns during peak hours. Needs manager review and approval to begin mitigation.',
    category: 'Operational',
    subcategory: 'Capacity',
    impact: 'Moderate',
    likelihood: 'Possible',
    status: 'Raised',
    ownerId: '1',
    createdByUserId: 'u1',
    department: 'Engineering',
    createdAt: new Date(2024, 10, 15).toISOString(),
    updatedAt: new Date(2024, 10, 15).toISOString(),
  },
  {
    id: 'r1',
    riskNo: 'R001',
    name: 'Third-Party API Outage',
    description: 'The primary payment processing API could experience downtime, preventing new customer sign-ups and payments.',
    category: 'Operational',
    subcategory: 'Third-party dependency',
    impact: 'Significant',
    likelihood: 'Likely',
    status: 'Open',
    ownerId: '1',
    createdByUserId: 'u1',
    department: 'Engineering',
    createdAt: new Date(2023, 10, 15).toISOString(),
    updatedAt: new Date(2023, 10, 15).toISOString(),
  },
  {
    id: 'r2',
    riskNo: 'R002',
    name: 'Data Breach via SQL Injection',
    description: 'A vulnerability in the user profile endpoint could allow attackers to access sensitive user data.',
    category: 'Security',
    subcategory: 'Application Vulnerability',
    impact: 'Severe',
    likelihood: 'Possible',
    status: 'In Progress',
    ownerId: '1',
    createdByUserId: 'u2',
    department: 'Engineering',
    createdAt: new Date(2023, 9, 20).toISOString(),
    updatedAt: new Date(2023, 11, 1).toISOString(),
  },
  {
    id: 'r3',
    riskNo: 'R001',
    name: 'Marketing Campaign Misalignment',
    description: 'The upcoming holiday marketing campaign may not align with the product features scheduled for release, leading to customer confusion.',
    category: 'Strategic',
    subcategory: 'Go-to-market',
    impact: 'Moderate',
    likelihood: 'Unlikely',
    status: 'Open',
    ownerId: '3',
    createdByUserId: 'u1',
    department: 'Marketing',
    createdAt: new Date(2023, 11, 5).toISOString(),
    updatedAt: new Date(2023, 11, 5).toISOString(),
  },
  {
    id: 'r4',
    riskNo: 'R001',
    name: 'Low Employee Morale',
    description: 'Recent organizational changes have led to a noticeable drop in team morale, potentially impacting productivity and retention.',
    category: 'People',
    subcategory: 'Engagement',
    impact: 'Minor',
    likelihood: 'Possible',
    status: 'Closed',
    ownerId: '4',
    createdByUserId: 'u2',
    department: 'HR',
    createdAt: new Date(2023, 8, 1).toISOString(),
    updatedAt: new Date(2023, 10, 10).toISOString(),
  },
];
